# Generated by Django 2.0.3 on 2018-03-21 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('type', '0003_auto_20180321_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary',
            name='comboListText',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='summary',
            name='medListText',
            field=models.TextField(),
        ),
    ]
