# Generated by Django 2.0.3 on 2018-03-22 23:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('type', '0004_auto_20180321_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='newID',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
