# Generated by Django 2.0.3 on 2018-03-22 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('type', '0004_auto_20180321_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
