# Generated by Django 2.0.3 on 2018-03-22 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('type', '0005_auto_20180322_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
