# Generated by Django 2.0.3 on 2018-03-31 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('type', '0010_auto_20180330_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyingas',
            name='choice',
            field=models.CharField(max_length=100),
        ),
    ]
