# Generated by Django 2.0.3 on 2018-03-31 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('type', '0011_auto_20180330_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyingas',
            name='choice',
            field=models.CharField(choices=[('Zachary Nowak', 'Zachary Nowak'), ('Not Zach', 'Not Zach')], max_length=100),
        ),
    ]
